.TH "HOPPER" "" "January 2015" "" ""
.SH "NAME"
\fBHopper\fR
.P
Hopper is a modular, opinionated, convention\-focused tool for your development
process\.
.P
Hopper's primary goal is to streamline switching between and contributing to a
variety of projects; regardless of language, testing library, architecture,
deployment strategy, etc\. If it's a hopper\-friendly project you should be able
to "hop" right in and get to work\.
.SH Usage
.P
Run \fBhop \-h\fR to see a list of commands\. \fBhop help <command>\fR will print out help
text for the given command\.
.P
\fBman hop\fR opens this README and supporting documentation\.
.SH Further Reading
.P
More information can be found in the online
docs \fIhttp://zincmade\.github\.io/hopper\fR\|\.

