#!/usr/bin/env node
var fs   = require('fs')
  , path = require('path');

var package = JSON.parse(fs.readFileSync(path.resolve(__dirname + '/../package.json')));
var program = require('commander')
program
  .version(package.version)
  .command('projects', 'lists all projects in your workspaces')
  .parse(process.argv)

if (program.args.length == 0) {
  program.help();
}
