#!/usr/bin/env node
fs   = require('fs');
path = require('path');

var package = JSON.parse(fs.readFileSync(path.resolve('package.json')));
var program = require('commander')
program
  .version(package.version)
  .command('projects', 'lists all projects in your workspaces')
  .parse(process.argv)
