#!/usr/bin/env node
// Back to [hop](./hop.html) command or [home](./index.html)
//
// Usage:
//
// ```sh
// # Add current working directory to set of workspaces
// $ hop workspaces add $(pwd)
// # Add the current working directory and allow it to contain sub-workspaces
// $ hop workspaces add --depth=2 $(pwd)
// ```

var program    = require('commander')
,   config     = require('../src/config')
,   workspaces = require('../src/workspaces');

program
  .usage('<path,...>')
  .description("Adds a path to the hopper's set of workspaces")
  .option('-d, --depth [n]', 'Depth to treat as workspaces. Defaults to 1',  parseInt)
  .parse(process.argv);

// If no workspace paths are provided, print the help text and quit.
if (program.args.length === 0) {
  program.help();
}

program.depth = program.depth || 1;
// Load configuration from standard config file.
var c = config.fromFile();

c.workspaces = workspaces.addPaths(c.workspaces || {}, program.args, program.depth);

config.toFile(c);
