#!/usr/bin/env node

var program = require('commander');
var expandHomeDir = require('expand-home-dir');
projects = require('../src/projects.js');
config   = require('../src/config.js');

program
  .parse(process.argv);

c = config.fromFile(expandHomeDir('~/.hop/config'));
projects.config.workspaces = c.workspaces;

var projectList = projects.all();
for (p in projectList) {
  console.log(projectList[p]);
}
