#!/usr/bin/env node
// Back to [hop](./hop.html) command or [home](./index.html)
//
// Usage:
//
// ```sh
// # Add current working directory to set of workspaces
// $ hop workspaces add $(pwd)
// # Add the current working directory and allow it to contain sub-workspaces
// $ hop workspaces add --depth=2 $(pwd)
// ```

// * [workspaces'  annotated-source](./src/workspaces.html)
// * [config's annotated-source](./src/config.html)

var program    = require('commander')
,   config     = require('../src/config')
,   workspaces = require('../src/workspaces');

program
  .usage('<path,...>')
  .description("Adds a path to the hopper's set of workspaces")
  .option('-d, --depth [n]', 'Depth to treat as workspaces. Defaults to 1',  parseInt)
  .parse(process.argv);

// If no workspace paths are provided, print the help text and quit.
if (program.args.length === 0) {
  program.help();
}

// Default depth option to 1
program.depth = program.depth || 1;

// Load configuration from standard config file.
var c = config.fromFile();

// Default to an empty dictionary if no workspaces configured already.
c.workspaces = c.workspaces || {};

// Set configured workspaces to workspaces + the passed in paths
c.workspaces = workspaces.addPaths(c.workspaces, program.args, program.depth);

// Save the configuration
config.toFile(c);
