#!/usr/bin/env node
// Back to [hop](./hop.html) command or [home](./index.html)
//
// Usage:
//
// ```sh
// # Print help text and exit
// $ hop workspaces
// ```
// ## Sub-commands:
// * [hop workspaces add](./hop-workspaces-add.html)
var program = require('commander');


program
  .command('add <path>', 'Adds the given path to your set of workspaces')
  .parse(process.argv);

// If no sub-commands are provided, print the help text and quit.
if (!program.runningCommand) {
  program.help();
}
